[package]
name = "maturin-crosscompilation-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "maturin_crosscompilation_example"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", features = [
  "extension-module",
  "generate-import-lib",
] }
