name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      - name: Install libsodium
        run: sudo apt-get update && sudo apt-get install -y libsodium-dev
      - name: Install minisign
        run: chmod +x scripts/install_minisign.sh && ./scripts/install_minisign.sh
      - name: Install zig
        run: chmod +x scripts/install_zig.sh && ./scripts/install_zig.sh
      - name: Install uv
        run: pip install uv
      - name: Build wheel
        run: uv tool run maturin build --target ${{ matrix.target }} --zig -i python3.10
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.target }}
          path: target/wheels/
